name: Test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test in dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: poetry run inv tests
